apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  labels: { app: portfolio }
spec:
  replicas: 2
  selector:
    matchLabels: { app: portfolio }
  template:
    metadata:
      labels: { app: portfolio }
    spec:
      containers:
      - name: portfolio
        image: asia-southeast1-docker.pkg.dev/valentino-project-471103/portfolio-repo/portfolio-app:latest
        ports:
        - containerPort: 80

